easy_admin:
    formats:
        datetime: 'd/m/Y'
    entities:
#        # List the entity class name you want to manage
      - App\Entity\BlogPost
      - App\Entity\User
      - App\Entity\Comment
